# Site settings
title: Entropy
header-img: img/home-bg.jpg
email: daniel.anechitoaie@gmail.com
description: "You always know a little more than they think you do, and a little less than you'd like to."
baseurl: ""
url: "http://daniel.anechitoaie.ro"
twitter_username: danechitoaie
bitbucket_username: danechitoaie
github_username: danechitoaie
facebook_username: daniel.anechitoaie

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["README.md"]
